name: Labeler

on: [pull_request]

jobs:
  label:
    name: Label PR
    runs-on: ubuntu-latest

    steps:
      - name: Label PR
        uses: actions/labeler@v6
        with:
          sync-labels: true
